Hello: Hello
List: List
Add: Add
Edit: Edit
Logout: Logout
Login: Login
Admin: Admin
LoginAs id@Text: Logged as #{id}

Title: Title
Author: Author
Type: Type
Category: Category
Tags: Tags
Tag: Tag
Thumbnail: Thumbnail
Upload: Upload
Url: Url
Download: Download
DownloadQ: Download?

UploadOrProvideUrl: You should upload a file or provide an url
FillAllRequired: Fill all required fields

Textbook: Textbook
LectureNotes: Lecture notes
OtherType: Other

Categories: Categories
Physics: Physics
Mathematics: Mathematics
Humanities: Humanities
