Hello: Hello
EntryList: List
EntryAdd: Add
EntryEdit: Edit
EntryDelete: Delete
Logout: Logout
Login: Login
Admin: Admin
LoginAs id@Text: Logged as #{id}

Title: Title
Author: Author
Type: Type
Category: Category
Tags: Tags
Thumbnail: Thumbnail
Upload: Upload
Url: Url
Download: Download
DownloadQ: Download?

UploadOrProvideUrl: You should upload a file or provide an url
FillAllRequired: Fill all required fields

Textbook: Textbook
LectureNotes: Lecture notes
OtherType: Other

Physics: Physics
Mathematics: Mathematics
Humanities: Humanities
