Hello: Здравствуйте
EntryList: Список
EntryAdd: Добавить
EntryEdit: Редактировать
EntryDelete: Удалить
Logout: Выйти
Login: Войти
Admin: Админка
LoginAs id@Text: Вы зашли как #{id}

Title: Заголовок
Author: Автор
Type: Тип
Category: Категория
Tags: Тэги
Thumbnail: Иконка
Upload: Залить
Url: Ссылка
Download: Скачать
DownloadQ: Закачать?

UploadOrProvideUrl: Залейте файл или укажите ссылку
FillAllRequired: Заполните все необходимые поля

Textbook: Учебник
LectureNotes: Лекции
OtherType: Другое

Categories: Категории
Physics: Физика
Mathematics: Математика
Humanities: Гуманитарные науки
