Default: &defaults
  user: "hbooks"
  password: ",fkfkfqrf"
  host: "localhost"
  port: 5432
  database: "hbooks"
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hbooks_test
  <<: *defaults

Staging:
  database: hbooks_staging
  poolsize: 100
  <<: *defaults

Production:
  user: "hvmorimqtdcuqw"
  password: "WPa2modq1lv9gspMClna_9q_0E"
  host: "ec2-184-73-162-34.compute-1.amazonaws.com"
  database: "d90r27bp7l474a"
  poolsize: 100
  <<: *defaults
