Default: &defaults
  user: "swish"
  password: ",fkfkfqrf"
  host: localhost
  port: 5432
  database: hbooks
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hbooks_test
  <<: *defaults

Staging:
  database: hbooks_staging
  poolsize: 100
  <<: *defaults

Production:
  database: hbooks_production
  poolsize: 100
  <<: *defaults
