Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://swish.dnsd.me:3000"
  copyright: Powered by Yesod
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://host-9ul.a.msu"
  <<: *defaults
