Default: &defaults
  host: "*4" # any IPv4 host
  port: 4321
  approot: "http://localhost:4321"
  copyright: Powered by Yesod
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://hbooks.herokuapp.com"
  <<: *defaults
