Default: &defaults
  database: hbooks.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hbooks_test.sqlite3
  <<: *defaults

Staging:
  database: hbooks_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: hbooks_production.sqlite3
  poolsize: 100
  <<: *defaults
